import { StyleSheet } from 'react-native';
import { C, palette, semantic } from './colors.js';
import { sp, type as T } from '../../tokens.js';

export const hoverStyles = StyleSheet.create({
  card: {
    position: 'fixed' as unknown as 'absolute',
    width: 260,
    backgroundColor: C.surface1,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: sp[7],
    zIndex: 9999,
    shadowColor: palette.black,
    shadowOffset: { width: 0, height: sp[4] },
    shadowOpacity: 0.5,
    shadowRadius: 16,
  },
  header: { flexDirection: 'row', alignItems: 'center', gap: sp[5], marginBottom: sp[5] },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: sp[4],
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: { fontSize: 13, fontWeight: '700', color: semantic.text.inverse },
  name: { fontSize: 13, fontWeight: '600', color: C.textPrimary, marginBottom: sp[1] },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sp[2],
    paddingHorizontal: 7,
    paddingVertical: sp[1],
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  statusDot: { width: 5, height: 5, borderRadius: 3 },
  statusText: { fontSize: 10, fontWeight: '500' },
  taskRow: {
    backgroundColor: C.surface3,
    borderRadius: 5,
    paddingHorizontal: sp[4],
    paddingVertical: sp[3],
    marginBottom: sp[5],
  },
  taskText: { ...T.monoXs, color: C.steel },
  metricsRow: { flexDirection: 'row', gap: sp[3], marginBottom: sp[5] },
  metric: {
    flex: 1,
    backgroundColor: C.surface3,
    borderRadius: 5,
    padding: sp[3],
    alignItems: 'center',
  },
  metricValue: { fontSize: 14, fontWeight: '600', color: C.textPrimary },
  metricLabel: { fontSize: 9, color: C.textTertiary, marginTop: 1 },
  errorText: { color: C.error },
  sparkLabel: {
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: C.textTertiary,
    marginBottom: sp[2],
  },
});
