/**
 * Workflow runtime → template-render integration test.
 *
 * Unlike e2e.test.ts (which mocks dispatchTemplate), this file exercises the
 * REAL dispatchTemplate to catch regressions where the runtime generates a
 * task ID format the renderer doesn't accept.
 *
 * Background: PR #142 changed the runtime to emit synthetic task IDs of the
 * form `workflow:<name>:<step>:<runId>` and PR #191 added the matching branch
 * in dispatchTemplate. Without this integration coverage, future drift
 * between the two layers would ship undetected (the unit test for
 * dispatchTemplate doesn't see the runtime's synthesis logic, and the
 * e2e test mocks the render away).
 *
 * Mocks ONLY `child_process.spawn` so the full
 * runtime → dispatchTemplate → dispatchTask → spawnClaude path runs for real
 * — without actually exec'ing a claude binary.
 */
import { describe, test, expect, beforeEach, afterEach, vi } from 'vitest';
import { randomUUID } from 'node:crypto';
import { mkdirSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { EventEmitter } from 'node:events';
import type { BrainDB } from '../../../../src/services/brain-db.js';
import type { BrainConfig } from '../../../../src/types.js';
import type { WorkflowFn } from '../../../../src/modules/workflow/runtime/types.js';
import { WorkflowRuntime } from '../../../../src/modules/workflow/runtime/runtime.js';
import {
  agentsMigrationV1,
  agentsMigrationV2,
  agentsMigrationV3,
} from '../../../../src/modules/agents/schema.js';
import { createTestDb, createMockEmbedder } from '../../../helpers.js';
import { createWorkflowRunsTable } from '../helpers.js';

// Mock at the lowest possible level: child_process.spawn. This exercises the
// REAL dispatchTask + resolveExplicitTask + dispatchTemplate path, so any
// regression where one of them rejects synthetic task IDs surfaces here.
const spawnedCalls: Array<{ args: string[]; cwd: string | undefined }> = [];

vi.mock('node:child_process', async (importOriginal) => {
  const actual = await importOriginal<typeof import('node:child_process')>();
  return {
    ...actual,
    spawn: vi.fn((_cmd: string, args: string[], opts: { cwd?: string }) => {
      spawnedCalls.push({ args, cwd: opts?.cwd });
      const proc = new EventEmitter() as EventEmitter & {
        pid: number;
        unref: () => void;
        kill: () => void;
        stdout: EventEmitter;
        stderr: EventEmitter;
      };
      proc.pid = 99999;
      proc.unref = () => {};
      proc.kill = () => {};
      proc.stdout = new EventEmitter();
      proc.stderr = new EventEmitter();
      return proc;
    }),
    execSync: actual.execSync,
  };
});

const minimalDispatchWorkflow: WorkflowFn = async (ctx) => {
  // 'implementation-compact' is a real template under src/modules/workflow/templates.
  // The synthetic task ID is generated by the runtime — if dispatchTemplate
  // rejects it (e.g. because of an unconditional getTask call), this throws
  // and the test fails.
  await ctx.dispatch('step-a', 'implementation-compact');
};

const embedder = createMockEmbedder();

let db: BrainDB;
let dbPath: string;
let notesDir: string;
let config: BrainConfig;

beforeEach(() => {
  ({ dbPath, db } = createTestDb());
  agentsMigrationV1.up(db.rawDb);
  agentsMigrationV2.up(db.rawDb);
  agentsMigrationV3.up(db.rawDb);
  createWorkflowRunsTable(db);
  notesDir = join(tmpdir(), `wf-integration-${randomUUID()}`);
  mkdirSync(notesDir, { recursive: true });
  config = {
    notesDir,
    dbPath,
    embedder: 'local',
    fusionWeights: { bm25: 0.3, vector: 0.7 },
  };
  spawnedCalls.length = 0;
  vi.clearAllMocks();
});

afterEach(() => {
  db.close();
  if (existsSync(notesDir)) {
    rmSync(notesDir, { recursive: true, force: true });
  }
});

describe('workflow runtime ↔ dispatchTemplate integration', () => {
  test('ctx.dispatch reaches subprocess spawn without rejecting synthetic task ID', async () => {
    const runtime = new WorkflowRuntime({ db, config, embedder });
    runtime.register('integration-min', minimalDispatchWorkflow);

    const runId = await runtime.start('integration-min', { project: 'VNM', projectDir: '/tmp' });

    // Wait until claude is spawned. The runtime → dispatchTemplate → dispatchTask
    // → spawnClaude path must reach this without anyone rejecting the synthetic
    // task ID. Whatever happens after the spawn (mock subprocess can't fully
    // satisfy setupProcessTracking) is irrelevant to the regression we're guarding.
    await vi.waitFor(() => expect(spawnedCalls.length).toBeGreaterThan(0), {
      timeout: 5000,
      interval: 50,
    });

    // claude was actually spawned exactly once — meaning the full
    // runtime → dispatchTemplate → dispatchTask → spawnClaude path ran.
    expect(spawnedCalls.length).toBe(1);
    // The synthetic task ID survived through to the spawn call args.
    const argsString = spawnedCalls[0].args.join(' ');
    expect(argsString).toMatch(/workflow:integration-min:step-a:/);

    // Cleanup so afterEach doesn't time out waiting for the agent.
    const running = runtime.activeRuns.get(runId);
    running?.ctx.resolveAgent('step-a', 'output');
  });

  test('dispatchTemplate rejects malformed runtime taskIds rather than silently rendering broken prompts', async () => {
    // This is a guard against regressions where someone re-introduces
    // unconditional getTask() but the test passes because every test
    // workflow happens to use real PM tasks. Synthetic IDs must fail loudly
    // when malformed.
    const { dispatchTemplate } =
      await import('../../../../src/modules/workflow/engine/dispatch.js');
    const result = await dispatchTemplate(
      db,
      config,
      embedder,
      'workflow:incomplete',
      'implementation-compact',
      { extraVars: { PROJECT_PREFIX: 'VNM' } }
    );
    expect(result.ok).toBe(false);
  });
});
